# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-28 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mandir', '0010_remove_mandir_user'),
        ('account', '0003_remove_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mandir', to='mandir.Mandir', verbose_name='mandir')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
