# Generated by Django 2.2.24 on 2021-08-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pan_card',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN Card'),
        ),
    ]
