# Generated by Django 2.2.24 on 2022-02-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_pan_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
            ],
        ),
    ]
