# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-15 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mandir', '0012_auto_20180714_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('phone_number', models.CharField(max_length=10, verbose_name='phone number')),
                ('name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('number_of_person', models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='number of person')),
            ],
            options={
                'verbose_name': 'Event Member',
                'verbose_name_plural': 'Event Members',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('description', models.CharField(max_length=255, verbose_name='Event Description')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, unique=True, verbose_name='end date')),
                ('status', models.BooleanField(default=True)),
                ('member_required', models.BooleanField(default=True)),
                ('mandir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandir_event', to='mandir.Mandir', verbose_name='mandir')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AddField(
            model_name='eventmember',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Events', verbose_name='event'),
        ),
    ]
