# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-15 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(max_length=1200, verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(verbose_name='start date'),
        ),
    ]
