# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-03 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180824_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(max_length=25000, verbose_name='Event Description'),
        ),
    ]
