# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-16 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='mandir name')),
                ('address', models.CharField(max_length=255, verbose_name='mandir location')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'Mandir',
                'verbose_name_plural': 'Mandirs',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(choices=[(1, 'Shanti Dhara'), (2, 'Abhishek'), (3, 'Chatra')], default=1)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('boli_date', models.DateTimeField(blank=True, null=True, verbose_name='boli date')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='payment date')),
                ('transaction_id', models.CharField(max_length=255, verbose_name='transaction id')),
                ('paid', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='account.Account', verbose_name='account')),
                ('mandir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandirs', to='mandir.Mandir', verbose_name='mandir')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
    ]
