# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(choices=[(1, 'Shanti Dhara'), (2, 'Abhishek'), (3, 'Chatra')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='record',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='transaction id'),
        ),
    ]
