# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-16 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0002_auto_20180616_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(choices=[('1', 'Shanti Dhara'), ('2', 'Abhishek'), ('3', 'Chatra')], default='1', max_length=2),
        ),
    ]
