# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0003_auto_20180616_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoliChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Boli Choice',
                'verbose_name_plural': 'Boli Choices',
            },
        ),
        migrations.CreateModel(
            name='MandirImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='path/', verbose_name='img')),
            ],
            options={
                'verbose_name': 'Mandir Image',
                'verbose_name_plural': 'MandirImages',
            },
        ),
        migrations.AddField(
            model_name='mandir',
            name='city',
            field=models.CharField(default='Pune', max_length=20, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='mandir',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=18.557024, max_digits=9, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='mandir',
            name='long',
            field=models.DecimalField(decimal_places=6, default=73.75092, max_digits=9, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='mandir',
            name='pin_code',
            field=models.CharField(default='411021', max_length=6, verbose_name='pin code'),
        ),
        migrations.AddField(
            model_name='mandir',
            name='state',
            field=models.CharField(default='maharashtr', max_length=10, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='bolichoices', to='mandir.BoliChoice', verbose_name='title'),
        ),
        migrations.AddField(
            model_name='mandirimage',
            name='mandir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandir_image', to='mandir.Mandir', verbose_name='mandir'),
        ),
    ]
