# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0004_auto_20180623_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mandirimage',
            options={'verbose_name': 'Mandir Image', 'verbose_name_plural': 'Mandir Images'},
        ),
        migrations.AddField(
            model_name='mandir',
            name='contract_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='contact number'),
        ),
        migrations.AddField(
            model_name='mandir',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
