# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0006_auto_20180623_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandirimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='mandirimage',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='mandirimage',
            name='image',
            field=models.ImageField(upload_to='pics/', verbose_name='image'),
        ),
    ]
