# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-24 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0007_auto_20180623_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandirimage',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='image'),
        ),
    ]
