# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-24 19:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mandir', '0008_auto_20180624_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandir',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
