# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-28 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0009_mandir_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandir',
            name='user',
        ),
    ]
