# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-14 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0010_remove_mandir_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandir',
            name='committee_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Committee name'),
        ),
    ]
