# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0011_mandir_committee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandir',
            name='address',
        ),
        migrations.AddField(
            model_name='mandir',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Mandir Description'),
        ),
        migrations.AddField(
            model_name='mandir',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
