# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-15 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0012_auto_20180714_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandirimage',
            name='event_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
