# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-12 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0013_mandirimage_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandir',
            name='Branch',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='mandir',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Account Name'),
        ),
        migrations.AddField(
            model_name='mandir',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='mandir',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='mandir',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='IFSC Code'),
        ),
    ]
