# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-12 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0014_auto_20180812_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mandir',
            old_name='Branch',
            new_name='branch',
        ),
    ]
