# Generated by Django 2.2.24 on 2021-10-23 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_pan_card'),
        ('mandir', '0016_record_remaining_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolichoice',
            name='request_choice',
            field=models.BooleanField(default=False, verbose_name='Request Choices'),
        ),
        migrations.AlterField(
            model_name='record',
            name='remaining_amt',
            field=models.IntegerField(default=0, verbose_name='Remaining amount'),
        ),
        migrations.CreateModel(
            name='BoliRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('boli_date', models.DateTimeField(blank=True, null=True, verbose_name='boli date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BR_accounts', to='account.Account', verbose_name='account')),
                ('mandir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BR_mandirs', to='mandir.Mandir', verbose_name='mandir')),
                ('title', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='BR_bolichoices', to='mandir.BoliChoice', verbose_name='title')),
            ],
            options={
                'verbose_name': 'Raise',
                'verbose_name_plural': 'Raise',
            },
        ),
    ]
