# Generated by Django 2.2.24 on 2021-10-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0017_auto_20211023_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='request_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BoliRequest',
        ),
    ]
