# Generated by Django 2.2.24 on 2021-11-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0018_auto_20211023_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandir',
            name='whatsapp_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Whatsapp Message'),
        ),
        migrations.AddField(
            model_name='mandir',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Whatsapp number'),
        ),
    ]
