# Generated by Django 2.2.24 on 2022-08-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0018_auto_20211023_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='VratDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='vrat name')),
                ('enabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('vrat_date', models.DateTimeField(auto_now_add=True, verbose_name='vrat date')),
                ('amount', models.IntegerField(verbose_name='amount')),
            ],
            options={
                'verbose_name': 'Vrat Detail',
                'verbose_name_plural': 'Vrat Details',
            },
        ),
        migrations.AddField(
            model_name='mandir',
            name='whatsapp_message',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Whatsapp Message'),
        ),
        migrations.AddField(
            model_name='mandir',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Whatsapp number'),
        ),
    ]
