# Generated by Django 2.2.24 on 2021-11-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0019_auto_20211106_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandir',
            name='whatsapp_message',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Whatsapp Message'),
        ),
    ]
