# Generated by Django 2.2.24 on 2022-08-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0019_auto_20220813_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vratdetail',
            name='amount',
        ),
        migrations.AlterField(
            model_name='vratdetail',
            name='vrat_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='vrat date'),
        ),
    ]
