# Generated by Django 2.2.24 on 2022-02-20 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandir', '0020_auto_20211106_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandir',
            name='facebook_page',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Facebook PageName'),
        ),
        migrations.CreateModel(
            name='MandirDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='mandir name')),
                ('status', models.BooleanField(default=True)),
                ('mandir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandir_domain', to='mandir.Mandir', verbose_name='mandir')),
            ],
            options={
                'verbose_name': 'Mandir Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
    ]
